### ISSUE TITLE
Read OID items within the Subject Directory Name

### ISSUE THREAD

**Issue by WalterB-MAMC** [AVVI94/fASN1.NET#1]
How does one use this library to get the values stored in the `Subject Directory Name` portion of the user certificate. I need to get the text value for the `OID 1.3.6.1.5.5.7.9.4 Country of Citizenship`. I do not see any examples on how to get this or any other items within the Subject Directory Name portion of the certificate.

**Comment by AVVI94** [comment]
Hi,

I've added functionality to parse the Subject Directory Attributes (SDA) into a class. You can find an example of how to do this [here](https://github.com/AVVI94/fASN1.NET/tree/master?tab=readme-ov-file#get-subject-director-attributes-sda-from-a-certificate).

According to [RFC 3739](https://www.rfc-editor.org/rfc/rfc3739.html#page-9), the CountryOfCitizenship attribute can be specified multiple times in a certificate. To support this, it is exposed as a read-only list of strings.

> The countryOfCitizenship attribute SHALL, when present, contain
> the identifier of at least one of the subject's claimed countries
> of citizenship at the time the certificate was issued.  If more
> than one country of citizenship is specified, each country of
> citizenship SHOULD be specified through a separate, single-valued
> countryOfCitizenship attribute.  Determination of citizenship is a
> matter of law and is outside the scope of this document.

Let me know if you have any questions or need further help. I'm happy to assist!

**Comment by WalterB-MAMC** [comment]
Thanks for adding this. I use smart cards every day for work and building web apps to read the smart card is a pain.

Anyways want to thank you and let you know the example code it slightly wrong.

`bool sda = SubjectDirectoryAttributes.FromCertificate(cert);` should be this:
`var sda = SubjectDirectoryAttributes.FromCertificate(cert);`

**Comment by AVVI94** [comment]
Thanks for letting me know - I’ve updated the example.

Working with smart cards is challenging, even outside of web applications. I deal with them very often at work, and honestly, it can be exhausting! They're slow, constantly prompt for a PIN, and all interactions involve unmanaged code, making debugging a nightmare. And don’t even get me started on how X509Store is still so Windows-centric, with no practical way to use it with smart cards on Linux or macOS 😄.

Anyway, I built this library mainly for myself—to avoid working with Bouncy Castle and X509Extensions. I’m glad to hear it might also be useful for others! 😅
